### ISSUE TITLE
Errors on run

### ISSUE THREAD

**Issue by Sanady** [gwenf/gridsome-strapi-tutorial#2]
Hello, 

I tried to run your project which I really liked. But there are few errors which are showing up:
```
npm run develop

> e-vents-front@ develop C:\laragon\www\gridsome-strapi-tutorial\e-vents-front
> gridsome develop

Gridsome v0.7.19

Initializing plugins...
Error: Request failed with status code 403
    at createError (C:\laragon\www\gridsome-strapi-tutorial\e-vents-front\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\laragon\www\gridsome-strapi-tutorial\e-vents-front\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\laragon\www\gridsome-strapi-tutorial\e-vents-front\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! e-vents-front@ develop: `gridsome develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the e-vents-front@ develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ivan\AppData\Roaming\npm-cache\_logs\2020-09-04T10_16_31_415Z-debug.log
```

Is there any solution?

**Comment by gwenf** [comment]
Hey, I'm not sure. Maybe the plugins aren't installed? Did you run `npm install`?
If you are still having trouble, please join my Discord and post about it there: https://discord.gg/FYbdFHq

**Comment by tourdefran** [comment]
Hi Gwen, 
I'm having the same issue with the Front, the Strapi part works fine!
Any clue? 
Thanks, very fancy project by the way

```
fran@frans-iMac e-vents-front % npm run develop 

> e-vents-front@ develop /Users/fran/Documents/gridsome-strapi-tutorial/e-vents-front
> gridsome develop

Gridsome v0.7.19

Initializing plugins...
Error: Request failed with status code 403
    at createError (/Users/fran/Documents/gridsome-strapi-tutorial/e-vents-front/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/fran/Documents/gridsome-strapi-tutorial/e-vents-front/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/fran/Documents/gridsome-strapi-tutorial/e-vents-front/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! e-vents-front@ develop: `gridsome develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the e-vents-front@ develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fran/.npm/_logs/2020-12-14T22_34_51_653Z-debug.log
fran@frans-iMac e-vents-front % 
```
